In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import tournamentGameByGameCleaning as tGGC

In [2]:
tournamentGameByGame = tGGC.getTournamentGameByGame()
tournamentGameByGame.describe()

              Year       Seed1       Seed2       Round      spread         id
count   441.000000  441.000000  441.000000  441.000000  441.000000  441.00000
mean   2016.000000    4.784580    8.777778    0.904762    4.877551  220.00000
std       2.002271    3.220155    4.795884    1.192781   14.052611  127.44999
min    2013.000000    1.000000    1.000000    0.000000  -29.000000    0.00000
25%    2014.000000    2.000000    4.000000    0.000000   -4.000000  110.00000
50%    2016.000000    5.000000    9.000000    0.000000    5.000000  220.00000
75%    2018.000000    7.000000   13.000000    1.000000   14.000000  330.00000
max    2019.000000   16.000000   16.000000    5.000000   47.000000  440.00000

In [3]:
tournamentGameByGame

     Year       Team1  Seed1           Team2  Seed2  Round  spread winner   id
0    2013     indiana      1   james madison     16      0      21  Team1    0
1    2013    nc state      8          temple      9      0      -4  Team2    1
2    2013        unlv      5      california     12      0      -3  Team2    2
3    2013    syracuse      4         montana     13      0      47  Team1    3
4    2013      butler      6        bucknell     11      0      12  Team1    4
..    ...         ...    ...             ...    ...    ...     ...    ...  ...
436  2019      purdue      3       tennessee      2      2       5  Team1  436
437  2019    virginia      1          purdue      3      3       5  Team1  437
438  2019    virginia      1          auburn      5      4       1  Team1  438
439  2019  texas tech      3  michigan state      2      4      10  Team1  439
440  2019    virginia      1      texas tech      3      5       8  Team1  440

[441 rows x 9 columns]

In [4]:
prevTournamentStats = pd.read_csv('March Madness Data/Historical Data/mdf.csv')
prevTournamentStats = prevTournamentStats.drop(['TEAM.1', 'ROUND', 'SEED'], axis=1)
prevTournamentStats

,YEAR,TEAM,KENPOM ADJUSTED EFFICIENCY,KENPOM ADJUSTED OFFENSE,KENPOM ADJUSTED DEFENSE,KENPOM ADJUSTED TEMPO,BARTTORVIK ADJUSTED EFFICIENCY,BARTTORVIK ADJUSTED OFFENSE,BARTTORVIK ADJUSTED DEFENSE,BARTHAG,...,3PT RATE DEFENSE,OP ASSIST %,OP O REB %,OP D REB %,BLOCKED %,TURNOVER % DEFENSE,WINS ABOVE BUBBLE,WIN %,POINTS PER POSSESSION OFFENSE,POINTS PER POSSESSION DEFENSE
0,2019,virginia,35.7,123.6,87.9,59.3,33.9,122.6,88.7,0.976,...,40.9,43.9,25.9,70.0,8.4,17.8,11.1,90.63,1.171,0.898
1,2019,duke,32.0,120.1,88.1,72.2,31.0,119.3,88.3,0.970,...,34.7,48.7,29.7,63.9,8.0,19.8,11.2,85.29,1.129,0.913
2,2019,gonzaga,32.8,125.1,92.3,69.8,32.5,124.1,91.6,0.971,...,34.6,41.1,27.1,69.4,4.9,18.9,7.1,90.91,1.241,0.909
3,2019,north carolina,29.2,119.9,90.7,74.3,28.0,119.2,91.2,0.956,...,42.5,54.7,23.2,65.4,11.1,18.5,10.0,81.82,1.126,0.955
4,2019,michigan st.,31.4,121.7,90.4,67.4,28.1,120.0,91.9,0.956,...,37.0,53.1,26.8,65.9,8.3,14.9,10.6,82.35,1.144,0.951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,2013,north carolina a&t,-5.3,92.6,97.9,64.8,-5.2,90.7,95.9,0.345,...,38.2,57.4,33.4,69.8,11.2,23.6,-11.5,52.94,0.920,0.917
472,2013,southern,-0.3,99.0,99.3,62.8,-0.7,96.3,97.0,0.479,...,30.1,41.6,31.1,73.3,8.7,20.3,-5.7,68.97,1.019,0.894
473,2013,western kentucky,-1.0,101.8,102.8,63.8,-1.3,99.2,100.5,0.463,...,31.7,44.6,31.1,65.2,10.8,20.7,-8.4,55.88,0.998,0.987
474,2013,liberty,-9.5,100.5,110.0,63.8,-10.4,97.9,108.3,0.239,...,33.1,51.6,32.9,70.7,10.6,15.2,-15.6,37.50,1.009,1.060
475,2013,liu brooklyn,-1.4,111.1,112.4,66.7,-3.2,108.2,111.4,0.417,...,30.6,53.9,33.3,65.0,9.5,18.4,-8.6,60.61,1.122,1.078

In [5]:
prevTournamentStats[((prevTournamentStats['TEAM'] == 'michigan state') & (prevTournamentStats['YEAR'] == 2019))]

Empty DataFrame
Columns: [YEAR, TEAM, KENPOM ADJUSTED EFFICIENCY, KENPOM ADJUSTED OFFENSE, KENPOM ADJUSTED DEFENSE, KENPOM ADJUSTED TEMPO, BARTTORVIK ADJUSTED EFFICIENCY, BARTTORVIK ADJUSTED OFFENSE, BARTTORVIK ADJUSTED DEFENSE, BARTHAG, ELITE SOS, BARTTORVIK ADJUSTED TEMPO, 2PT %, 3PT %, FREE THROW %, EFG %, FREE THROW RATE, 3PT RATE, ASSIST %, OFFENSIVE REBOUND %, DEFENSIVE REBOUND %, BLOCK %, TURNOVER %, 2PT % DEFENSE, 3PT % DEFENSE, FREE THROW % DEFENSE, EFG % DEFENSE, FREE THROW RATE DEFENSE, 3PT RATE DEFENSE, OP ASSIST %, OP O REB %, OP D REB %, BLOCKED %, TURNOVER % DEFENSE, WINS ABOVE BUBBLE, WIN %, POINTS PER POSSESSION OFFENSE, POINTS PER POSSESSION DEFENSE]
Index: []

[0 rows x 38 columns]

In [6]:
prevTournamentStats[prevTournamentStats['TEAM'] == 'michigan state']

Empty DataFrame
Columns: [YEAR, TEAM, KENPOM ADJUSTED EFFICIENCY, KENPOM ADJUSTED OFFENSE, KENPOM ADJUSTED DEFENSE, KENPOM ADJUSTED TEMPO, BARTTORVIK ADJUSTED EFFICIENCY, BARTTORVIK ADJUSTED OFFENSE, BARTTORVIK ADJUSTED DEFENSE, BARTHAG, ELITE SOS, BARTTORVIK ADJUSTED TEMPO, 2PT %, 3PT %, FREE THROW %, EFG %, FREE THROW RATE, 3PT RATE, ASSIST %, OFFENSIVE REBOUND %, DEFENSIVE REBOUND %, BLOCK %, TURNOVER %, 2PT % DEFENSE, 3PT % DEFENSE, FREE THROW % DEFENSE, EFG % DEFENSE, FREE THROW RATE DEFENSE, 3PT RATE DEFENSE, OP ASSIST %, OP O REB %, OP D REB %, BLOCKED %, TURNOVER % DEFENSE, WINS ABOVE BUBBLE, WIN %, POINTS PER POSSESSION OFFENSE, POINTS PER POSSESSION DEFENSE]
Index: []

[0 rows x 38 columns]

In [7]:
#Adding Kenpom Adjusted Efficiency for each team


kenPomAdjEffTeam1 = [];
kenPomAdjEffTeam2 = [];


for i in range(0,len(tournamentGameByGame)):
    teamRowJacob = tournamentGameByGame[tournamentGameByGame['id'] == i]
    team1Name = teamRowJacob.Team1
    #print(team1Name[i])
    team2Name = teamRowJacob.Team2
    year = teamRowJacob.Year
    #print(year[i])
    team1RowJack = prevTournamentStats[((prevTournamentStats['TEAM'] == team1Name[i]) & (prevTournamentStats['YEAR'] == year[i]))]
    team2RowJack = prevTournamentStats[((prevTournamentStats['TEAM'] == team2Name[i]) & (prevTournamentStats['YEAR'] == year[i]))]
    #print()
    
    #team1RowJack = prevTournamentStats.loc(prevTournamentStats['TEAM'])
    kenPomAdjEffTeam1Val = team1RowJack['KENPOM ADJUSTED EFFICIENCY']
    kenPomAdjEffTeam2Val = team2RowJack['KENPOM ADJUSTED EFFICIENCY']
    if(kenPomAdjEffTeam1Val.empty):
        kenPomAdjEffTeam1.append(None)
    else:
        #print(kenPomAdjEffTeam1Val[team1RowJack.index[0]])
        #print('--------------------')
        kenPomAdjEffTeam1.append(kenPomAdjEffTeam1Val[team1RowJack.index[0]])
        
    if(kenPomAdjEffTeam2Val.empty):
        kenPomAdjEffTeam2.append(None)
    else:
        #print(team2Name[i])
        #print(kenPomAdjEffTeam2Val[team2RowJack.index[0]])
        #print('--------------------')
        kenPomAdjEffTeam2.append(kenPomAdjEffTeam2Val[team2RowJack.index[0]])
    
tournamentGameByGame['KENPOM ADJUSTED EFFICIENCY TEAM1'] = kenPomAdjEffTeam1
tournamentGameByGame['KENPOM ADJUSTED EFFICIENCY TEAM2'] = kenPomAdjEffTeam2

tournamentGameByGame

,Year,Team1,Seed1,Team2,Seed2,Round,spread,winner,id,KENPOM ADJUSTED EFFICIENCY TEAM1,KENPOM ADJUSTED EFFICIENCY TEAM2
0,2013,indiana,1,james madison,16,0,21,Team1,0,29.9,-1.7
1,2013,nc state,8,temple,9,0,-4,Team2,1,NaN,12.0
2,2013,unlv,5,california,12,0,-3,Team2,2,17.2,12.7
3,2013,syracuse,4,montana,13,0,47,Team1,3,22.6,2.7
4,2013,butler,6,bucknell,11,0,12,Team1,4,14.8,13.4
...,...,...,...,...,...,...,...,...,...,...,...
436,2019,purdue,3,tennessee,2,2,5,Team1,436,26.1,27.0
437,2019,virginia,1,purdue,3,3,5,Team1,437,35.7,26.1
438,2019,virginia,1,auburn,5,4,1,Team1,438,35.7,23.3
439,2019,texas tech,3,michigan state,2,4,10,Team1,439,26.7,NaN
440,2019,virginia,1,texas tech,3,5,8,Team1,440,35.7,26.7

In [8]:
#Generalizing adding stat columns for all stat columns

statTeam1 = [];
statTeam2 = [];

statColName = 'KENPOM ADJUSTED OFFENSE'


for i in range(0,len(tournamentGameByGame)):
    teamRowJacob = tournamentGameByGame[tournamentGameByGame['id'] == i]
    team1Name = teamRowJacob.Team1
    #print(team1Name[i])
    team2Name = teamRowJacob.Team2
    year = teamRowJacob.Year
    #print(year[i])
    team1RowJack = prevTournamentStats[((prevTournamentStats['TEAM'] == team1Name[i]) & (prevTournamentStats['YEAR'] == year[i]))]
    team2RowJack = prevTournamentStats[((prevTournamentStats['TEAM'] == team2Name[i]) & (prevTournamentStats['YEAR'] == year[i]))]
    #print()
    
    #team1RowJack = prevTournamentStats.loc(prevTournamentStats['TEAM'])
    statTeam1Val = team1RowJack[statColName]
    statTeam2Val = team2RowJack[statColName]
    if(statTeam1Val.empty):
        statTeam1.append(None)
    else:
        #print(kenPomAdjEffTeam1Val[team1RowJack.index[0]])
        #print('--------------------')
        statTeam1.append(statTeam1Val[team1RowJack.index[0]])
        
    if(statTeam2Val.empty):
        statTeam2.append(None)
    else:
        #print(team2Name[i])
        #print(kenPomAdjEffTeam2Val[team2RowJack.index[0]])
        #print('--------------------')
        statTeam2.append(statTeam2Val[team2RowJack.index[0]])
    
tournamentGameByGame[f'{statColName} Team1'] = statTeam1
tournamentGameByGame[f'{statColName} Team2'] = statTeam2

tournamentGameByGame

,Year,Team1,Seed1,Team2,Seed2,Round,spread,winner,id,KENPOM ADJUSTED EFFICIENCY TEAM1,KENPOM ADJUSTED EFFICIENCY TEAM2,KENPOM ADJUSTED OFFENSE Team1,KENPOM ADJUSTED OFFENSE Team2
0,2013,indiana,1,james madison,16,0,21,Team1,0,29.9,-1.7,122.5,99.6
1,2013,nc state,8,temple,9,0,-4,Team2,1,NaN,12.0,NaN,111.5
2,2013,unlv,5,california,12,0,-3,Team2,2,17.2,12.7,106.9,107.4
3,2013,syracuse,4,montana,13,0,47,Team1,3,22.6,2.7,114.5,105.6
4,2013,butler,6,bucknell,11,0,12,Team1,4,14.8,13.4,110.1,107.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,2019,purdue,3,tennessee,2,2,5,Team1,436,26.1,27.0,121.1,122.5
437,2019,virginia,1,purdue,3,3,5,Team1,437,35.7,26.1,123.6,121.1
438,2019,virginia,1,auburn,5,4,1,Team1,438,35.7,23.3,123.6,119.6
439,2019,texas tech,3,michigan state,2,4,10,Team1,439,26.7,NaN,112.7,NaN
440,2019,virginia,1,texas tech,3,5,8,Team1,440,35.7,26.7,123.6,112.7