In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import sklearn as sk

In [2]:
df = pd.read_csv('finalData.csv')
df

,Year,Team1,Seed1,Team2,Seed2,Round,spread,winner,id,SEED Team1,...,3P_O Team1,3P_O Team2,3P_D Team1,3P_D Team2,ADJ_T Team1,ADJ_T Team2,WAB Team1,WAB Team2,WIN_RATE Team1,WIN_RATE Team2
0,2013,indiana,1,james madison,16,0,21,Team1,0,6.000000,...,40.3,33.6,30.4,34.7,67.8,64.2,7.8,-8.9,0.805556,0.583333
1,2013,nc state,8,temple,9,0,-4,Team2,1,11.000000,...,39.1,32.8,30.2,35.3,68.1,66.8,2.2,1.5,0.685714,0.705882
2,2013,unlv,5,california,12,0,-3,Team2,2,7.500000,...,32.6,30.2,31.6,33.6,69.3,66.5,1.8,0.5,0.705882,0.636364
3,2013,syracuse,4,montana,13,0,47,Team1,3,2.000000,...,33.4,36.4,28.4,33.3,65.4,63.9,5.1,-1.4,0.750000,0.766667
4,2013,butler,6,bucknell,11,0,12,Team1,4,7.250000,...,34.3,35.8,33.2,30.5,64.7,63.4,4.7,1.0,0.742857,0.818182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,2019,purdue,3,tennessee,2,2,5,Team1,436,5.333333,...,37.4,36.7,34.2,35.4,67.0,68.8,6.1,9.9,0.722222,0.861111
435,2019,virginia,1,purdue,3,3,5,Team1,437,3.333333,...,39.5,37.4,28.9,34.2,60.7,67.0,11.1,6.1,0.921053,0.722222
436,2019,virginia,1,auburn,5,4,1,Team1,438,3.333333,...,39.5,38.1,28.9,34.8,60.7,69.3,11.1,6.1,0.921053,0.769231
437,2019,texas tech,3,michigan state,2,4,10,Team1,439,5.500000,...,36.5,37.8,29.7,31.6,67.5,68.6,7.0,10.7,0.815789,0.820513
438,2019,virginia,1,texas tech,3,5,8,Team1,440,3.333333,...,39.5,36.5,28.9,29.7,60.7,67.5,11.1,7.0,0.921053,0.815789