In [68]:
import pandas as pd

In [79]:
df= pd.read_csv('Tournament Team Data (Including 2023).csv')
tournament_teams_13_19 = {

'Abilene Christian',

'Akron',

'Alabama',

'Alabama-Birmingham',

'Albany (NY)',

'American',

'Arizona',

'Arizona State',

'Arkansas',

'Auburn',

'Austin Peay',

'BYU',

'Baylor',

'Belmont',

'Bradley',

'Bucknell',

'Buffalo',

'Butler',

'Cal Poly',

'Cal State Bakersfield',

'Cal State Fullerton',

'California',

'Chattanooga',

'Cincinnati',

'Clemson',

'Coastal Carolina',

'Colgate',

'College of Charleston',

'Colorado',

'Colorado State',

'Creighton',

'Davidson',

'Dayton',

'Delaware',

'Duke',

'ETSU',

'Eastern Kentucky',

'Eastern Washington',

'Fairleigh Dickinson',

'Florida',

'Florida Gulf Coast',

'Florida State',

'Fresno State',

'Gardner-Webb',

'George Washington',

'Georgetown',

'Georgia',

'Georgia State',

'Gonzaga',

'Green Bay',

'Hampton',

'Harvard',

'Hawaii',

'Holy Cross',

'Houston',

'Illinois',

'Indiana',

'Iona',

'Iowa',

'Iowa State',

'Jacksonville State',

'James Madison',

'Kansas',

'Kansas State',

'Kent State',

'Kentucky',

'LSU',
'La Salle',
'Lafayette',
'Liberty',
'Lipscomb',
'Little Rock',
'Louisiana',
'Louisville',
'Loyola (IL)',
'Manhattan',
'Marquette',
'Marshall',
'Maryland',
'Memphis',
'Mercer',
'Miami (FL)',
'Michigan',
'Michigan State',
'Middle Tennessee',
'Milwaukee',
'Minnesota',
'Mississippi State',
'Missouri',
'Montana',
"Mount St. Mary's",
'Murray State',
'NC State',
'Nebraska',
'Nevada',
'New Mexico',
'New Mexico State',
'North Carolina A&T',
'North Carolina Central',
'North Dakota',
'North Dakota State',
'Northeastern',
'Northern Iowa',
'Northern Kentucky',
'Northwestern',
'Northwestern State',
'Notre Dame',
'Ohio State',
'Oklahoma',
'Oklahoma State',
'Old Dominion',
'Ole Miss',
'Oregon',
'Oregon State',
'Pacific',
'Penn',
'Pitt',
'Princeton',
'Providence',
'Purdue',
'Radford',
'Rhode Island',
'Robert Morris',
'SMU',
'Saint Louis',
"Saint Mary's",
'San Diego State',
'Seton Hall',
'South Carolina',
'South Dakota State',
'Southern',
'St. Bonaventure',
"St. John's (NY)",
"St. Joseph's",
'Stanford',
'Stephen F. Austin',
'Stony Brook',
'Syracuse',
'TCU',
'Temple',
'Tennessee',
'Texas',
'Texas A&M',
'Texas Southern',
'Texas Tech',
'Troy',
'Tulsa',
'UC-Davis',
'UC-Irvine',
'UCF',
'UCLA',
'UConn',
'UMBC',
'UMass',
'UNC',
'UNC Asheville',
'UNC Greensboro',
'UNC Wilmington',
'UNLV',
'USC',
'Utah',
'Utah State',
'VCU',
'Valparaiso',
'Vanderbilt',
'Vermont',
'Villanova',
'Virginia',
'Virginia Tech',
'Washington',
'Weber State',
'West Virginia',
'Western Kentucky',
'Western Michigan',
'Wichita State',
'Winthrop',
'Wisconsin',
'Wofford',
'Wright State',
'Wyoming',
'Xavier',
'Yale'
}
tournament_teams_13_19 = {ele.lower() for ele in tournament_teams_13_19}

names = ['virginia', 'north carolina', 'michigan st.', 'florida st.', 'kansas st.', 'mississippi st.', 'iowa st.', 'mississippi', 'utah st.', 'ohio st.', 'arizona st.', 'st. john\'s', 'murray st.', 'new mexico st.', 'uc irvine', 'georgia st.', 'gardner webb', 'north dakota st.', 'prairie view a&m', 'wichita st.', 'miami fl', 'north carolina st.', 'loyola chicago', 'san diego st.', 'south dakota st.', 'wright st.', 'cal st. fullerton', 'liu brooklyn', 'oklahoma st.', 'wake forest', 'east tennessee st.', 'kent st.', 'jacksonville st.', 'uc davis', 'new orleans', 'oregon st.', 'saint joseph\'s', 'connecticut', 'pittsburgh', 'arkansas little rock', 'fresno st.', 'cal st. bakersfield', 'weber st.', 'boise st.', 'uab', 'albany', 'north florida', 'massachusetts', 'louisiana lafayette', 'colorado st.', 'northwestern st.']
def replace_st(df):
    for i, name in df['TEAM'].iteritems():
        if name == "virginia" or name == "mississippi" or name == "new orleans" or name == "connecticut" or name == "pittsburgh":
            continue
        elif name.endswith("st."):
            df.at[i, 'TEAM'] = name.replace("st.", "state")
    return df

df = df.drop(df[df['YEAR'] < 2013].index)
df = df.drop(df[df['YEAR'] > 2019].index)
df['TEAM'] = df['TEAM'].replace('Texas A&M CC', 'Texas A&M')
df['TEAM'] = df['TEAM'].str.lower()
replace_st(df)
df['TEAM'] = df['TEAM'].replace('east tennessee state', 'etsu')
df['TEAM'] = df['TEAM'].replace('arkansas little rock', 'little rock')
df['TEAM'] = df['TEAM'].replace('gardner webb', 'gardner-webb')
df['TEAM'] = df['TEAM'].replace('pittsburgh', 'pitt')
df['TEAM'] = df['TEAM'].replace('uc davis', 'uc-davis')
df['TEAM'] = df['TEAM'].replace('connecticut', 'uconn')
df['TEAM'] = df['TEAM'].replace('cal st. fullerton', 'cal state fullerton')
df['TEAM'] = df['TEAM'].replace('cal st. bakersfield', 'cal state bakersfield')
df['TEAM'] = df['TEAM'].replace('massachusetts', 'umass')
df['TEAM'] = df['TEAM'].replace("saint joseph's", "st. joseph's")
df['TEAM'] = df['TEAM'].replace("north carolina state", "nc state")
df['TEAM'] = df['TEAM'].replace('uc irvine', 'uc-irvine')
df['TEAM'] = df['TEAM'].replace("louisiana lafayette", "louisiana")
df['TEAM'] = df['TEAM'].replace("mississippi", "ole miss")
df['TEAM'] = df['TEAM'].replace("loyola chicago", "loyola (il)")
df['TEAM'] = df['TEAM'].replace("miami fl", "miami (fl)")
df['TEAM'] = df['TEAM'].replace("albany", "albany (ny)")
df['TEAM'] = df['TEAM'].replace("st. john's", "st. john's (ny)")
df['TEAM'] = df['TEAM'].replace("north carolina", "unc")
df['TEAM'] = df['TEAM'].replace("uab", "alabama-birmingham")




sunm = 0
for n in tournament_teams_13_19:
    if n not in df['TEAM'].unique():
        sunm += 1
        print(n)
print(f"# of missing teams: {sunm}")

# for m in df['TEAM'].unique():
#     if m not in tournament_teams_13_19:
#         print(m)

# return rows where TEAM contains "opp"
# for m in tournament_teams_13_19:
#     if 'opp' in m:
#         print(m)
# print("=====================================")
df.reset_index(drop=True, inplace=True)
df.to_csv('cleaned-names.csv', index=False)

test = pd.read_csv('cleaned-names.csv')
df.loc[(df['TEAM'].str.contains('mount'))]

# of missing teams: 0

,YEAR,SEED,TEAM,ROUND,KENPOM ADJUSTED EFFICIENCY,KENPOM ADJUSTED OFFENSE,KENPOM ADJUSTED DEFENSE,KENPOM ADJUSTED TEMPO,BARTTORVIK ADJUSTED EFFICIENCY,BARTTORVIK ADJUSTED OFFENSE,...,OP ASSIST %,OP O REB %,OP D REB %,BLOCKED %,TURNOVER % DEFENSE,WINS ABOVE BUBBLE,WIN %,POINTS PER POSSESSION OFFENSE,POINTS PER POSSESSION DEFENSE,TEAM.1
198,2017,16,mount st. mary's,64,-4.2,99.0,103.2,66.8,-3.6,98.0,...,43.9,34.5,77.0,7.9,21.7,-7.9,55.88,0.992,0.996,Mount St. Mary's
406,2014,16,mount st. mary's,68,-3.8,107.5,111.2,68.4,-4.3,107.3,...,45.3,33.1,71.7,8.3,18.8,-9.4,50.00,1.077,1.101,Mount St. Mary's